# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np

1. Crear un arreglo de ceros de longitud 12

In [ ]:
zero = np.zeros(12)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [ ]:
array= np.zeros(10)
array[4] = 10
array

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

3. Crear un arreglo que tenga los números del 10 al 49

In [ ]:
a= np.arange(1, 50)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [ ]:
a_2d = np.arange(9)
a_2d = a_2d.reshape(3, 3)

print(a_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [ ]:
a_r=np.random.rand(100)
print(f"la media es : {a_r.mean()}")
print(f"la varianza es : {a_r.var()}")

la media es : 0.48745826563905936
la varianza es : 0.09530344558423931


6. Calcular la media de un arreglo usando np.sum

In [ ]:
media=a_r.sum()/(a_r.size)
media

0.48745826563905936

7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [ ]:
varianza= np.sum((a_r- media) ** 2) / a_r.size
print(f"la varianza es : {varianza}")

la varianza es : 0.09530344558423931


8. Crear un array de números aleatorios usando np.random.randn.
Esta distribución normal estándar tiene una media de 0 y una desviación estándar de 1


In [ ]:
array_r2=np.random.randn(10)
array_r2

array([ 0.24574129,  1.08385147,  1.43189618,  1.41295072,  2.07886354,
       -1.58315832, -1.01000576, -0.10262404,  0.42794487,  0.21149351])